# Dependencies
markdown:         redcarpet
pygments:         false
rouge:            true

# Permalinks
permalink:        pretty

# Setup
title:            Benja Duran 
tagline:          The Jekyll Butler
description:      Base theme for Jekyll themes by @mdo.
url:              http://localhost:4000

author:
  name:           Mark Otto
  url:            https://twitter.com/mdo

paginate:         3

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole
