# Dependencies
markdown:         redcarpet
highlighter:       pygments

# Permalinks
permalink:        pretty

# Setup
title:            Benja Durán 
tagline:          
description:      Blog de benja duran
url:              https://benjad.github.io/

author:
  name:          ' Benja Duran'
  url:            https://twitter.com/

paginate:         3

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/benjad/benjad.github.io

 # This is the list of pages to incldue in the header of the website.
pages_list:       {'Posts':'/archive','Sobre mi':'/about'}

+safe: true
+lsi: false

